---
:request:
  :url: https://api.alve.com/products/1135844
  :headers:
    :accept: application/vnd.alve+json; version=3
    :authorization: Bearer 41Z9Muu7C6qpERTbKnLFLwx2dOYozAAFf4LSIz8PHL1j5ngi5zAz1n17BtasAISp4RReR3sF4zGrohCxB88dw==
  :verb: GET
:response:
  :status: 200
  :headers:
    server: nginx
    content-type: application/json; charset=utf-8
    vary: Accept-Encoding
    x-ratelimit-limit: '100'
    x-ratelimit-remaining: '98'
    x-ratelimit-reset: '1429778340'
    status: 200 OK
    cache-control: max-age=300, private
    x-ua-compatible: IE=Edge,chrome=1
    x-request-id: '1393270904'
    x-runtime: '0.019779'
    x-dns-prefetch-control: 'off'
    access-control-allow-origin: "*"
    access-control-allow-methods: HEAD, GET, POST, PUT, DELETE
    x-app: as1_ssl
    content-length: '258'
    accept-ranges: bytes
    date: Thu, 23 Apr 2015 08:38:51 GMT
    x-varnish: '1393270904'
    age: '0'
    via: 1.1 varnish
    connection: close
    x-origin: lb1
    x-cache: MISS
  :body: '{"product":{"id":1135844,"name":"Samsung Galaxy S4 i9500 16Gb Siyah Cep
    Telefonu","sku_id":146414,"shop_id":77,"category_id":33,"availability":null,"click_url":"https://www.alve.com/products/show/1135844?client_id=IY3bKctJtHYqbo57IFxTuA%3D%3D&from=api","shop_uid":"22374","expenses":null,"price":1155.24}}'
:created_at: 2015-04-23 11:34:40.959447466 +03:00
