---
:request:
  :url: https://api.alve.com/shops/42/products/search?shop_uid=86711
  :headers:
    :accept: application/vnd.alve+json; version=3
    :authorization: Bearer 41Z9Muu7C6qpERTbKnLFLwx2dOYozAAFf4LSIz8PHL1j5ngi5zAz1n17BtasAISp4RReR3sF4zGrohCxB88dw==
  :verb: GET
:response:
  :status: 200
  :headers:
    server: nginx
    content-type: application/json; charset=utf-8
    vary: Accept-Encoding
    x-ratelimit-limit: '100'
    x-ratelimit-remaining: '97'
    x-ratelimit-reset: '1429778340'
    status: 200 OK
    x-ua-compatible: IE=Edge,chrome=1
    cache-control: max-age=0, private, must-revalidate
    x-request-id: '215486086'
    x-runtime: '0.028134'
    x-dns-prefetch-control: 'off'
    access-control-allow-origin: "*"
    access-control-allow-methods: HEAD, GET, POST, PUT, DELETE
    x-app: as1_ssl
    content-length: '292'
    accept-ranges: bytes
    date: Thu, 23 Apr 2015 08:38:51 GMT
    x-varnish: '215486086'
    age: '0'
    via: 1.1 varnish
    connection: close
    x-origin: lb2
    x-cache: MISS
  :body: '{"products":[{"id":497997,"name":"iPad Mini 16 GB Wi-fi Beyaz MD531","sku_id":75873,"shop_id":42,"category_id":19,"availability":null,"click_url":"https://www.alve.com/products/show/497997?client_id=IY3bKctJtHYqbo57IFxTuA%3D%3D&from=api","shop_uid":"86711","expenses":null,"price":620.7}],"meta":{"pagination":{"total_results":1,"total_pages":1,"page":1,"per":25}}}'
:created_at: 2015-04-23 11:34:41.097437163 +03:00
