---
:request:
  :url: https://api.alve.com/shops/42/products/search?shop_uid=86711
  :headers:
    :accept: application/vnd.alve+json; version=3
    :authorization: Bearer fiw8se9i6Wtv/h2ejPKFZoDWJL1o1RSK6PdqgVXhVC5DXLdpvT//4F/TWSYfvEk0PmCefo5fOR68eBPTyxEdw==
  :verb: GET
:response:
  :status: 200
  :headers:
    !binary "c2VydmVy": nginx
    !binary "Y29udGVudC10eXBl": application/json; charset=utf-8
    !binary "dmFyeQ==": Accept-Encoding
    !binary "c3RhdHVz": 200 OK
    !binary "eC11YS1jb21wYXRpYmxl": IE=Edge,chrome=1
    !binary "Y2FjaGUtY29udHJvbA==": max-age=0, private, must-revalidate
    !binary "eC1yZXF1ZXN0LWlk": '989916535'
    !binary "eC1ydW50aW1l": '0.104416'
    !binary "eC1kbnMtcHJlZmV0Y2gtY29udHJvbA==": 'off'
    !binary "eC1hcHA=": as2_ssl
    !binary "Y29udGVudC1sZW5ndGg=": '284'
    !binary "YWNjZXB0LXJhbmdlcw==": bytes
    !binary "ZGF0ZQ==": Mon, 15 Sep 2014 10:07:34 GMT
    !binary "eC12YXJuaXNo": '989916535'
    !binary "YWdl": '0'
    !binary "dmlh": 1.1 varnish
    !binary "Y29ubmVjdGlvbg==": close
    !binary "eC1vcmlnaW4=": varnish1
    !binary "eC1jYWNoZQ==": MISS
  :body: ! '{"products":[{"id":497997,"name":"iPad Mini 16 GB Wi-fi Beyaz MD531","sku_id":75873,"shop_id":42,"category_id":19,"availability":null,"click_url":"https://www.alve.com/products/show/497997?client_id=Bn9IVZbjL27QolcUwH1gA%3D%3D&from=api","shop_uid":"86711","price":639.13}],"meta":{"pagination":{"total_results":1,"total_pages":1,"page":1,"per":25}}}'
:created_at: 2014-09-15 13:07:34.315025148 +03:00
