---
:request:
  :url: http://api.skroutz.gr/shops/452/products/search?shop_uid=95F
  :headers:
    :accept: application/vnd.skroutz+json; version=3.1
    :authorization: Bearer VSkzjtrNKLUAkOUFNBHv5vRrDjMowQXQ0uqKElVEds3GCcE5oBn/lqWKIkwkHONY57MbbB/rSzFVr/sDjGyN5w==
  :verb: :get
:response:
  :status: 200
  :headers:
    server: nginx
    date: Wed, 05 Oct 2016 13:59:53 GMT
    content-type: application/json; charset=utf-8
    vary: Accept-Encoding
    x-ratelimit-limit: '100'
    x-ratelimit-remaining: '64'
    x-ratelimit-reset: '1475676000'
    x-frame-options: SAMEORIGIN
    x-xss-protection: 1; mode=block
    x-content-type-options: nosniff
    etag: W/"4913812ba640e176eb998db5e3a31657"
    cache-control: max-age=0, private, must-revalidate
    x-request-id: '688303668'
    x-runtime: '0.021457'
    x-dns-prefetch-control: 'off'
    access-control-allow-origin: "*"
    access-control-allow-methods: HEAD, GET, POST, PUT, DELETE
    x-app: rontok
    x-varnish: '688303667'
    age: '0'
    via: 1.1 varnish-v4
    x-origin: lb1
    x-cache: MISS
    x-cached: skroutz miss(0)
    accept-ranges: bytes
    content-length: '93'
    connection: close
  :body: '{"products":[],"meta":{"pagination":{"total_results":0,"total_pages":0,"page":1,"per":25}}}'
:created_at: 2016-10-05 16:59:53.485759127 +03:00
