---
:request:
  :url: https://api.skroutz.gr/products/29878439
  :headers:
    :accept: application/vnd.skroutz+json; version=3.1
    :authorization: Bearer 3D41-2x3B8Oxh05DKD-sdLrpUKDs_q6bgmwhn5n6uWznwED1-9UpjoIqLAvDPe9XTY3JH8pvmFnOQ-SS2jgJBA==
  :verb: :get
:response:
  :status: 200
  :headers:
    access-control-allow-origin: "*"
    access-control-request-method: "*"
    date: Fri, 26 Jan 2018 16:43:42 GMT
    content-type: application/json; charset=utf-8
    cache-control: max-age=300, private
    etag: W/"27bd8ba3e38cbb9164f349bae418b3dc"
    x-request-id: 97f90b8e-b612-4ea9-bdf4-1a82a77a10b9
    x-runtime: '0.439096'
    server: WEBrick/1.3.1 (Ruby/2.3.3/2016-11-21)
    content-length: '790'
    connection: close
    set-cookie: locale=el_GR; path=/
  :body: '{"product":{"id":29878439,"name":"Apple iPhone 5S Space Grey 16 GB EU (
    ✔ΔΩΡΟ ΘΗΚΗ + ✔TEMPERED GLASS )","sku_id":3783654,"shop_id":4102,"category_id":40,"availability":"Παράδοση
    1 έως 3 ημέρες","click_url":"https://www.skroutz.gr/products/show/29878439?client_id=XIbz2_n2p94JTskRpHu9wQ%3D%3D\u0026from=api","shop_uid":"548","expenses":null,"web_uri":"http://skroutz.gr:3000/products/show/29878439","sizes":[],"blp":{"shipping_cost":4.41,"payment_method_cost":3.5,"final_price":297.81},"price":289.9,"immediate_pickup":false},"meta":{"personalization":{"location":{"address_id":25522,"label":"Αλέκου
    Παναγούλη 91, Νέα Ιωνία","lat":"38.043322","lng":"23.760006","type":"address","country_code":"GR"},"payment_method":{"type":"spot_cash"}}}}'
:created_at: 2018-01-26 18:43:42.862433135 +02:00
